# 持久卷
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: nfs
spec:
  storageClassName: ""
  capacity:
    storage: 20Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 8.210.203.126
    path: /data/nfs