controller:
  adminSecret: false
  additionalPlugins:
    - blueocean:1.25.2
    - blueocean-jira:1.25.2
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "1024m"
      memory: "3072Mi"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    hostName: jenkins.local

persistence:
  enabled: true
  existingClaim: jenkins-pvc
  storageClass: ""
  accessMode: "ReadWriteMany"
  size: "5Gi"